### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by simonnelli** [jonalaniz/Scouter#1]
I've added the API Module to freescout but after entering the Instance URL and the API key, nothing happens when clicking on 'Get Mailboxes'. Can't give any more specific info as there is no error message.

**Comment by simonnelli** [comment]
Tried with http instead of https. Doesn't work either but shows a truncated error message. See screenshot
![CleanShot 2024-12-02 at 14 24 59@2x](https://github.com/user-attachments/assets/5448152a-498d-4762-a278-6eda7dc6dd09)

**Comment by ilyakonovalenko** [comment]
The app does not work for me as well. It loads mailboxes and that's all.

**Comment by simonnelli** [comment]
For me it doesn't even load the mailboxes

**Comment by jonalaniz** [comment]
@ilyakonovalenko does it show any error next tot he "Get Mailboxes" button or in the menu bar?

**Comment by simonnelli** [comment]
No unfortunately no error message

**Comment by ilyakonovalenko** [comment]
> @ilyakonovalenko does it show any error next tot he "Get Mailboxes" button or in the menu bar?

No, it loads mailboxes but clicking on the button to save does nothing.

**Comment by simonnelli** [comment]
Also tested with https://demo.freescout.net/ and its API Key. Login works here, the demo mailbox is loaded but the preferences can't be saved. After just quitting the App and reopening. The app is configured correctly, so the preferences were saved but the GUI didn't reflect this without restarting the app.

With my own instance login doesn't even work and therefore the mailboxes are not loaded.

**Comment by jonalaniz** [comment]
@ilyakonovalenko @simonnelli does the Mailbox show up greyed out or is it selectable?

**Comment by simonnelli** [comment]
At first greyed out, after restarting the app selectable. Try it yourself with the demo instance https://demo.freescout.net/

**Comment by simonnelli** [comment]
Could one issue with login be with installs in subfolders? I've installed FreeScout on my host under .../support. The instance url is https://domain.com/support.

**Comment by jonalaniz** [comment]
Fixed two issues.
1. When I refactored the Scouter controller I failed to set it as a delegate so it didn't update when configuration changed.
2. The window's controller was not removing the old mailboxes from the mailbox selector.

I know these aren't the exact issues that were originally posted, but do ya'll mind checking these and seeing if this makes any difference? It is supposed to show errors either inside of the preferences window if it is a mailbox issue or in the menu bar if it is an issue with the folders/conversations.

[Scouter-1.0.6.zip](https://github.com/user-attachments/files/17979778/Scouter-1.0.6.zip)

**Comment by simonnelli** [comment]
No change for me with 1.0.6.

**Comment by jonalaniz** [comment]
> Could one issue with login be with installs in subfolders? I've installed FreeScout on my host under .../support. The instance url is https://domain.com/support.

This may be our issue, I will configure my instance under a subfolder and test.

**Comment by jonalaniz** [comment]
Here is another build. I found that instances on subdirectories were not handled properly by Scouter.

The change has been made and I have tested it with a couple different servers, let me know how this works for you.

[Scouter-1.0.6(3).zip](https://github.com/user-attachments/files/17981448/Scouter-1.0.6.3.zip)

**Comment by simonnelli** [comment]
The save button works, but there is no visual feedback that the preferences were saved. This should be improved.
