### ISSUE TITLE
Quit Scouter

### ISSUE THREAD

**Issue by simonnelli** [jonalaniz/Scouter#4]
If scouter isn't configured the app can only be quit by quitting it in activity monitor. Clicking the menubar icon doesn't offer a way to quit the app or to reopen Scouter Preferences to finish the initial setup.

**Comment by jonalaniz** [comment]
Can I get a screenshot of what it shows, in theory  it should always add these static menu items wether it authenticates or not.

<img width="436" alt="Screenshot 2024-12-02 at 7 29 26 AM" src="https://github.com/user-attachments/assets/f3846d9a-8fcb-44f3-ae6a-84a16f821f87">

**Comment by simonnelli** [comment]
Nothing is shown. The Icon lights up when clicked in the menubar but otherwise nothing happens

**Comment by jonalaniz** [comment]
Figured out the problem, was corrected in the latest commit and will be in the upcoming update.
