### ISSUE TITLE
1.0.8 breaks functionality

### ISSUE THREAD

**Issue by simonnelli** [jonalaniz/Scouter#7]
1.0.8 completely breaks the app for me. On first launch I get a blank preferences dialogue (1.0.7 was setup correctly before).
After filling out URL and API Key the Mailbox is detected correctly but neither fetch interval nor folders can be configured (greyed out). Closing the preferences dialogue leaves the app unconfigured and therefore not working.

**Comment by jonalaniz** [comment]
I found the issue in it not activating the pop-up buttons. Can you try 1.0.9 and tell me if this issue persists?

**Comment by jonalaniz** [comment]
Great! Yeah, this was a great idea.
